### PR TITLE
Added Silence

### PR DESCRIPTION
**Pull request by agu-borrego**
Added the Silence framework: https://github.com/DEAL-US/Silence

### CODE REVIEW

**Comment by dbohdan** [comment]
Does Silence satisfy this requirement from [CONTRIBUTING](https://github.com/dbohdan/automatic-api/blob/master/CONTRIBUTING.md)?

> It should respond to changes to the database schema with no or minimal user intervention (e.g., a restart or a SIGHUP).

**Comment by agu-borrego** [comment]
Yes, Silence issues an independent SQL query per request so it can easily handle changes in the database while it is running with no intervention.

**Comment by dbohdan** [comment]
This does seems to fit, but I need to clarify: if I have executed the command  `silence createapi && silence run` and then perform a database migration while Silence is running, what do I need to do in order to update the API to match the new database schema?

**Comment by agu-borrego** [comment]
In that case, yes. Every endpoint generated by Silence is linked to a SQL query, so if the schema itself changes because of a migration or any other reason, the endpoints themselves would need to be regenerated and reloaded, which in the current version of Silence requires a restart. In that case, you could just execute `silence createapi && silence run` again and the new updated endpoints would be loaded.

**Comment by dbohdan** [comment]
Thanks for explaining. Added in 2e3d6c2.

**Pull request closed without merging**
