### PR TITLE
Add PathQL

### PR DESCRIPTION
**Pull request by mevdschee**
I hope you are willing to add this new (automatic) API type and it's reference implementation.

### CODE REVIEW

**Comment by dbohdan** [comment]
Interesting to see a new project from the developer of PHP-CRUD-API.  Is this ready for production?  The project has few commits so far and scarce documentation.

You've edited the readme directly.  Please follow the guidelines in `CONTRIBUTING.md` and submit a data file.

**Comment by dbohdan** [comment]
I **am** willing to add a new type of API.  PathQL is a clever idea.  The website has convinced me that it is at least worth trying.

**Comment by mevdschee** [comment]
Wow.. that is great! will (try to) grow the community around it in the upcoming months.

**Comment by dbohdan** [comment]
Closing, as PathQL-Go has not been updated since 2019. You are welcome to resubmit PathQL-Go if work on it resumes.

**Comment by mevdschee** [comment]
No worries, I understand.

**Pull request closed without merging**
