### PR TITLE
A good Rails solution for automatic API creation

### PR DESCRIPTION
**Pull request by lorint**
Rails gem enabling auto-creation of RESTful APIs by using just a few lines of code.

### CODE REVIEW

**Comment by dbohdan** [comment]
Sorry, this is out of scope. See [CONTRIBUTING](https://github.com/dbohdan/automatic-api/blob/ddc117117d24c7efeef9ede79ba4bf0f4817ef10/CONTRIBUTING.md).

**Comment by lorint** [comment]
> Sorry, this is out of scope.

Curious as to how this could be out of scope -- the gem auto-creates everything necessary to expose API endpoints and documentation.

Did you see the [video](https://github.com/lorint/brick/blob/master/docs/api.md)?  It goes from **rails new** to APIs with six added lines of code :)

**EDIT:**  Have now made a quick 3 minute video showing just the essentials to expose an API layer for a database:

https://user-images.githubusercontent.com/5301131/213666717-09218064-9737-4a21-a345-5c270065c83b.mp4

Hopefully The Brick will be deemed worthy!

**Comment by dbohdan** [comment]
While The Brick may be the best thing since sliced bread for Rails devs, my list is focused on standalone programs. Anything that requires you to maintain a codebase, even small, is not what I am looking for.

**Comment by lorint** [comment]
Hmmm, perhaps I will create a standalone version of Brick -- similar to how PostgREST works.

Hmmm.......

**Pull request closed without merging**
