### PR TITLE
Create happysql

### PR DESCRIPTION
**Pull request by moul**

### CODE REVIEW

**Comment by dbohdan** [comment]
How mature is HappySQL? It looks like something that's been used in production, but I don't see any tests for the server part.

**Comment by moul** [comment]
Will create issues on the repo :)

**Comment by dbohdan** [comment]
That sounds good, but it doesn't exactly answer my question about maturity.&nbsp;:-) The issue mentions that you plan to document how your company uses HappySQL in production. You can tell me that in a few words here and it will be enough for me.

**Comment by tamsanh** [comment]
FYI @dbohdan, HappySQL has not moved for two years, since the PR was added. I think you're ok to close this with no merge.

**Comment by dbohdan** [comment]
@moul What is the development status of HappySQL?

**Comment by moul** [comment]
As @tamsanh said it before, the repo has not moved for two years

HappySQL is used in production since that time and never required any change for now

I can't speak about the maturity of our own needs, but the current version of the software is mature enough to cover them

---

To be honest, I don't give a fuck if you close this PR without merging it, my open-source spirit forced me to propose this software on places where other people are happy to discover new alternatives

I can understand that you only accept the most used/favorited/still-active ones :+1:

**Comment by dbohdan** [comment]
It speaks to HappySQL's quality that it has been running in production this whole time.  However, I would still rather not add software without tests.  Since the project isn't abandoned, I don't see a reason to close the PR.  I will keep it open in case more development happens and tests are added.

**Comment by tamsanh** [comment]
My apologies @moul; I assumed the project was abandoned due to lack of movement. Will do better than to assume, next time around. Thank you for the due diligence, @dbohdan.

**Comment by dbohdan** [comment]
The repository has been archived. Closing. Please resubmit if there is ongoing development in some other repository.

**Pull request closed without merging**
